name = "Sublime Hugo"
license = "MIT"
licenselink = "//github.com/dt801ts/sublime-hugo-theme/LICENSE.MD"
description = "hugo theme"
homepage = "//github.com/dt801ts/sublime-hugo-theme"
tags = ["blog", "minimal", "syntax highlighting", "dev"]
features = ["", ""]
min_version = 0.17

# Ported from:
[original]
  name = "Mathieu Mayer-Mazzoli"
  homepage = "//mx3m.github.io"
  repo = "//github.com/mx3m/hikari-for-Jekyll"