# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

# Design by TEMPLATED
# http://templated.co
# Released for free under the Creative Commons Attribution License

# Name       : Assembly
# Description: A two-column, fixed-width design with dark color scheme.
# Version    : 1.1
# Released   : 2018-09-11

name = "Hugo Assembly"
license = "MIT"
licenselink = "https://github.com/salsysd/hugo-assembly/blob/master/LICENSE"
description = "Assembly: A nice modern business-style design."
tags = ["modern","company","simple","clean"]
features = ["services","about-us","contact", "welcome"]
min_version = "0.41"

[author]
  name = "Salomon Valverde"
  homepage = "https://salomon.io"

# If porting an existing theme
[original]
  name = "Assembly"
  homepage = "http://templated.co"
  repo = ""
