name = "Anybody Home"
license = "MIT"
licenselink = "https://github.com/lasseborly/anybodyhome/blob/master/LICENSE.md"
description = "A simple theme for simple people with simple needs"
homepage = "https://github.com/lasseborly/anybodyhome/"
tags = ["clean", "simple"]
features = ["highlightjs", "Blog only"]
min_version = 0.16

[author]
  name = "Lasse Borly"
  homepage = "https://lasseborly.com/"
