name = "BeyondNothing"
license = "MIT"
licenselink = "https://github.com/salcan/BeyondNothing/blob/master/LICENSE"
description = "Simplest Hugo theme possible"
homepage = "https://cloudconfusing.com/"
min_version = 0.14
tags = ["blog", "lander", "minimalist", "clean"]
features = "nothing yet"

[author]
  name = "Cloud Confusing"
  homepage = "https://cloudconfusing.com/"
