baseURL = "http://example.org/"
languageCode = "en-us"
title = "SimpleIT Hugo theme demo website"
theme = 'simpleit-hugo-theme'
#disqusShortname = "simpleit-hugo-theme"
#googleAnalytics = "UA-64047109-4"
# If site is in subfolder e.g.: example.com/blog then
# set canonifyURLs to true to generate absolute paths
#canonifyURLs = true

# Build robots.txt file
enableRobotsTXT = true
enableGitInfo = true #makes .Lastmod (on Page) to be fetched from Git

# syntax highlighting
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

# Theme variables
#
[params]
  # Description/subtitle for homepage (can be Markdown)
  description = "SimpleIT is a Hugo theme with mobile-first design."

  # Render Share buttons static or with javascript
  shareButtonsType = "static" #<static|javascript>

  # Format dates with Go's time formatting
  date_format = "Mon Jan 02, 2006"

  # Your copyright notice - appears in site footer.
  # To display a copyright symbol, type `&copy;`.
  copyright = "<small>&copy; 2018</small>"

  # used in page level ads in head
  #google_adsense_id = "ca-pub-1234567890"
  
  # verification string for Google Webmaster Tools
  #google_verify_meta = "1234567890"

  # verification string for Bing Webmaster Tools
  #bing_verify_meta = "1234567890"

  # verification string for Yandex Webmaster Tools
  #yandex_verify_meta = "1234568790"

  # site handler
  twitter = "simpleitrocks"

  # Buymeacoffe id (https://buymeacoffee.com)
  # buymeacoffe = marcanuy

  [params.author]
  name = "Marcelo Canina"
  country = "Uruguay"
  twitter = 'marcanuy'
  website = 'https://marcanuy.com'
  gravatar = "2ebdffd5ddb4a98b0cc77117503d2711"
  google_plus = "118415138433063920612"
  linkedin = "marcelocanina"
  mail = "me@marcanuy.com"
  github = "marcanuy"
  gitlab = "marcanuy"
  stackexchange = "1193189"
  bio = "OSS enthusiast."

