[build]
publish = "exampleSite/public"

[context.production]
command = "ln -s repo ../engimo && hugo --source=exampleSite --themesDir=../..  --baseURL=${URL}"

[context.branch-deploy]
command = "ln -s repo ../engimo && hugo --source=exampleSite --themesDir=../.. --baseURL=${DEPLOY_PRIME_URL}"

[context.deploy-preview]
command = "ln -s repo ../engimo && hugo --source=exampleSite --themesDir=../..  --baseURL=${DEPLOY_PRIME_URL}"

[build.environment]
HUGO_VERSION = "0.45"
