# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Rusty"
license = "MIT"
licenselink = "https://github.com/cecyc/hugo-theme-rusty/blob/master/LICENSE"
description = "Clean, pink, typography-oriented theme for Hugo"
homepage = "https://github.com/cecyc/hugo-theme-rusty"
tags = ["clean", "type", "blog", "pink"]
features = ["blog"]
min_version = "0.41"

[author]
  name = "Cecy Correa"
  homepage = "https://cecycorrea.com"
