defaults: &defaults
  working_directory: techlog-simple
  docker:
    - image: mazgi/hugo-static-website:hugo-0.49-2018.10.1

version: 2
jobs:
  deploy_to_firebase:
    <<: *defaults
    steps:
      - checkout
      - run: cd exampleSite && sed -i '1ipublishDir = "public/techlog-simple"' config.toml
      - run: cd exampleSite && sed -i '1igoogleAnalytics = "'${GOOGLE_ANALYTICS_TRACKING_ID}'"' config.toml
      - run:
          name: Build Website
          command: cd exampleSite && hugo --baseURL="https://${GCLOUD_PROJECT}.firebaseapp.com/techlog-simple" --themesDir="../.."
      - run:
          name: Deploy to Firebase
          command: cd exampleSite && firebase deploy --project="${GCLOUD_PROJECT}" --token="${FIREBASE_TOKEN}"

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - deploy_to_firebase:
          filters:
            branches:
              only: master
