# End your baseURL with a `/` trailing slash, e.g. `https://example.com/`.
baseURL = "https://example.com/"

languageCode = "en-us"
title = "Hugo Theme One"
theme = "one"
googleAnalytics = "UA-123-45"

# Chroma Syntax Highlighting
pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true
pygmentsStyle = "pygments"

[params]
    navigation = ["archives.md", "about.md"]

