name = "Bingo"
license = "MIT"
licenselink = "https://github.com/gundamew/hugo-bingo/blob/master/LICENSE"
description = "Nothing but texts."
homepage = "https://github.com/gundamew/hugo-bingo"
tags = ["minimalist", "simple", "clean", "blog", "starter", "responsive"]
features = ["blog"]
min_version = "0.42.2"

[author]
  name = "Bing-Sheng Chen"
  homepage = "https://bschen.tw/"

[original]
  name = "Kellen Evan Person"
  homepage = "https://goodroot.ca/"
  repo = "https://github.com/goodroot/hugo-classic"
