baseURL = "http://example.org/"
languageCode = "en-us"
title = "SimpleIT Hugo theme demo website"
theme = 'simpleit-hugo-theme'
disqusShortname = "simpleit-hugo-theme"
googleAnalytics = "UA-64047109-4"
canonifyURLs = true

# Build robots.txt file
enableRobotsTXT = true

# syntax highlighting
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

# Theme variables
#
[params]
  # Description/subtitle for homepage (can be Markdown)
  description = "SimpleIT is a Hugo theme with mobile-first design."

  # Render Share buttons static or with javascript
  shareButtonsType = "static" #<static|javascript>

  # Format dates with Go's time formatting
  date_format = "Mon Jan 02, 2006"

  # site handler
  twitter = "simpleitrocks"

  # Buymeacoffe id (https://buymeacoffee.com)
  buymeacoffe = "marcanuy"

  [params.author]
  name = "Marcelo Canina"
  country = "Uruguay"
  twitter = 'marcanuy'
  website = 'https://marcanuy.com'
  gravatar = "2ebdffd5ddb4a98b0cc77117503d2711"
  linkedin = "marcelocanina"
  mail = "me@marcanuy.com"
  github = "marcanuy"
  gitlab = "marcanuy"
  stackexchange = "1193189"
  bio = "OSS enthusiast."

